SELECT 
"TRIP"."TRIP_ID",
"TRIP"."TRIP_IOS_ID", 
"VESSEL"."VESSEL_NAME",
"FISH"."FE_MAJOR_LEVEL_ID",
"FISH"."FE_TOTAL_CATCH_WEIGHT",
"LINK"."CATCH_ID",
"CATCH"."SPECIES_CODE",
"SPECIES"."SPECIES_COMMON_NAME",
"SPECIES"."SPECIES_SCIENCE_NAME",
"CATCH"."CATCH_WEIGHT",
"CATCH"."CATCH_COUNT",
"CATCH"."CATCH_VERIFICATION_CODE",
"VERIF"."CATCH_VERIFICATION_DESC"

FROM 
"GFBioSQL"."dbo"."B01_TRIP" AS "TRIP"  
	JOIN  
	"GFBioSQL"."dbo"."C_Vessels" AS "VESSEL"
		ON 
		"TRIP"."VESSEL_ID" = "VESSEL"."VESSEL_ID" 

	JOIN  
	"GFBioSQL"."dbo"."B02_FISHING_EVENT" AS "FISH"
		ON 
		"TRIP"."TRIP_ID" = "FISH"."TRIP_ID" 
	JOIN  
	"GFBioSQL"."dbo"."B02L3_Link_Fishing_Event_Catch" AS "LINK"
		ON 
		"FISH"."FISHING_EVENT_ID" = "LINK"."FISHING_EVENT_ID" 
	JOIN  
	"GFBioSQL"."dbo"."B03_CATCH" AS "CATCH"
		ON 
		"LINK"."CATCH_ID" = "CATCH"."CATCH_ID" 
	JOIN  
	"GFBioSQL"."dbo"."C_Catch_Verification" AS "VERIF"
		ON 
		"CATCH"."CATCH_VERIFICATION_CODE" = "VERIF"."CATCH_VERIFICATION_CODE" 
	JOIN  
	"GFBioSQL"."dbo"."C_Species" AS "SPECIES"
		ON 
		"CATCH"."SPECIES_CODE" = "SPECIES"."SPECIES_CODE" 

WHERE "TRIP"."TRIP_ID" = 00000
ORDER BY "FISH"."FE_MAJOR_LEVEL_ID";

