
-- create morpho table

SELECT 
"TRIP"."TRIP_ID",
"VESSEL"."VESSEL_NAME",
"FISH"."FE_MAJOR_LEVEL_ID",
"CATCH"."CATCH_ID",
"SPECIES"."SPECIES_COMMON_NAME",
"SPECIES"."SPECIES_SCIENCE_NAME",
"SAMPLE_TYPE"."SAMPLE_TYPE_DESC",
"SAMPLE"."SAMPLE_TYPE_COMMENT",
"SPECIMEN"."SAMPLE_ID",
"SPECIMEN"."SPECIMEN_ID",
"SPECIMEN"."SPECIMEN_SEX_CODE",
"SPECIMEN"."SPECIMEN_AGE",
"MORPHO"."SPECIMEN_MORPHOMETRICS_VALUE",
"MORPHO_UNIT"."MORPHOMETRICS_UNIT_DESC",
"MORPHO_DESC"."MORPHOMETRICS_ATTRIBUTE_DESC"

FROM 
"GFBioSQL"."dbo"."B01_TRIP" AS "TRIP"  
	JOIN  
	"GFBioSQL"."dbo"."C_Vessels" AS "VESSEL"
		ON 
		"TRIP"."VESSEL_ID" = "VESSEL"."VESSEL_ID" 
	JOIN  
	"GFBioSQL"."dbo"."B02_FISHING_EVENT" AS "FISH"
		ON 
		"TRIP"."TRIP_ID" = "FISH"."TRIP_ID" 
	JOIN  
	"GFBioSQL"."dbo"."B02L3_Link_Fishing_Event_Catch" AS "LINK"
		ON 
		"FISH"."FISHING_EVENT_ID" = "LINK"."FISHING_EVENT_ID"
	JOIN  
	"GFBioSQL"."dbo"."B03_CATCH" AS "CATCH"
		ON 
		"LINK"."CATCH_ID" = "CATCH"."CATCH_ID" 
	JOIN  
	"GFBioSQL"."dbo"."C_Species" AS "SPECIES"
		ON 
		"CATCH"."SPECIES_CODE" = "SPECIES"."SPECIES_CODE" 
	JOIN  
	"GFBioSQL"."dbo"."B03L4_Link_Catch_Sample" AS "LINK2"
		ON 
		"CATCH"."CATCH_ID" = "LINK2"."CATCH_ID" 
	JOIN  
	"GFBioSQL"."dbo"."B04_SAMPLE" AS "SAMPLE"
		ON 
		"LINK2"."SAMPLE_ID" = "SAMPLE"."SAMPLE_ID" 
	JOIN  
	"GFBioSQL"."dbo"."C_Sample_Type" AS "SAMPLE_TYPE"
		ON 
		"SAMPLE"."SAMPLE_TYPE_CODE" = "SAMPLE_TYPE"."SAMPLE_TYPE_CODE" 
	JOIN  
	"GFBioSQL"."dbo"."B05_SPECIMEN" AS "SPECIMEN"
		ON 
		"LINK2"."SAMPLE_ID" = "SPECIMEN"."SAMPLE_ID" 
	JOIN  
	"GFBioSQL"."dbo"."B05d_Specimen_Morphometrics" AS "MORPHO"
		ON 
		"SPECIMEN"."SPECIMEN_ID" = "MORPHO"."SPECIMEN_ID" 
	JOIN  
	"GFBioSQL"."dbo"."C_Morphometrics_Unit" AS "MORPHO_UNIT"
		ON 
		"MORPHO"."MORPHOMETRICS_UNIT_CODE" = "MORPHO_UNIT"."MORPHOMETRICS_UNIT_CODE" 
	JOIN  
	"GFBioSQL"."dbo"."C_Morphometrics_Attribute" AS "MORPHO_DESC"
		ON 
		"MORPHO"."MORPHOMETRICS_ATTRIBUTE_CODE" = "MORPHO_DESC"."MORPHOMETRICS_ATTRIBUTE_CODE" 




WHERE "TRIP"."TRIP_ID" = 00000
ORDER BY "FISH"."FE_MAJOR_LEVEL_ID";
